// <auto-generated />
using System;
using ClinicAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicAPI.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    partial class ClinicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicAPI.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int>("AppointmentStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ComplaintReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CreatedByAspNetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("SlotEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("SlotStartTime")
                        .HasColumnType("time");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Appointm__8ECDFCC234F9E7BB");

                    b.HasIndex("AppointmentStatusId");

                    b.HasIndex("CreatedByAspNetUserId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Appointment", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.AppointmentStatus", b =>
                {
                    b.Property<int>("AppointmentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentStatusId"));

                    b.Property<string>("AppointmentStatus1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AppointmentStatus");

                    b.HasKey("AppointmentStatusId")
                        .HasName("PK__Appointm__A619B660F625695B");

                    b.HasIndex(new[] { "AppointmentStatus1" }, "UQ__Appointm__BABC6966ECC57928")
                        .IsUnique();

                    b.ToTable("AppointmentStatus", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.AppointmentStatusHistory", b =>
                {
                    b.Property<int>("AppointmentStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentStatusHistoryId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("ChangedByAspNetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentStatusHistoryId")
                        .HasName("PK__Appointm__BD119A9D10F52473");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("AppointmentStatusId");

                    b.HasIndex("ChangedByAspNetUserId");

                    b.ToTable("AppointmentStatusHistory", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.DoctorLeave", b =>
                {
                    b.Property<int>("DoctorLeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorLeaveId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedByAspNetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("LeaveStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("DoctorLeaveId")
                        .HasName("PK__DoctorLe__B1CB912B446FF000");

                    b.HasIndex("ApprovedByAspNetUserId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("LeaveStatusId");

                    b.ToTable("DoctorLeave", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.DoctorProfile", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("AspNetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DoctorId")
                        .HasName("PK__DoctorPr__2DC00EBF2B67E9C5");

                    b.HasIndex("AspNetUserId");

                    b.HasIndex(new[] { "LicenseNumber" }, "UQ__DoctorPr__E88901666FFDCB7D")
                        .IsUnique();

                    b.ToTable("DoctorProfile", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.DoctorSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SlotDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ScheduleId")
                        .HasName("PK__DoctorSc__9C8A5B49BD74EEC9");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorSchedule", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.DoctorSpecialization", b =>
                {
                    b.Property<int>("DoctorSpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorSpecializationId"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("DoctorSpecializationId")
                        .HasName("PK__DoctorSp__14F6ED4D30E323BD");

                    b.HasIndex("SpecializationId");

                    b.HasIndex(new[] { "DoctorId", "SpecializationId" }, "UQ_DoctorSpecialization")
                        .IsUnique();

                    b.ToTable("DoctorSpecialization", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.LeaveStatus", b =>
                {
                    b.Property<int>("LeaveStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveStatusId"));

                    b.Property<string>("LeaveStatus1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LeaveStatus");

                    b.HasKey("LeaveStatusId")
                        .HasName("PK__LeaveSta__75EE81FAC79A0D52");

                    b.HasIndex(new[] { "LeaveStatus1" }, "UQ__LeaveSta__8A6C54D169C428B9")
                        .IsUnique();

                    b.ToTable("LeaveStatus", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("AspNetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E126219CA94");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("AspNetUserId");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.NotificationType", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationTypeId"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NotificationTypeId")
                        .HasName("PK__Notifica__299002C1F1C752F7");

                    b.HasIndex(new[] { "Type" }, "UQ__Notifica__F9B8A48BC37A2A65")
                        .IsUnique();

                    b.ToTable("NotificationType", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.PatientProfile", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("AspNetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BloodType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Cprnumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CPRNumber");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PatientReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PatientId")
                        .HasName("PK__PatientP__970EC366847975D2");

                    b.HasIndex("AspNetUserId");

                    b.HasIndex(new[] { "PatientReferenceNumber" }, "UQ__PatientP__8C7D9721B58AD64C")
                        .IsUnique();

                    b.HasIndex(new[] { "Cprnumber" }, "UQ__PatientP__BD136F743CE5CFA6")
                        .IsUnique();

                    b.ToTable("PatientProfile", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("PrescriptionStatusId")
                        .HasColumnType("int");

                    b.Property<int>("VisitRecordId")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionId")
                        .HasName("PK__Prescrip__401308327312BAF5");

                    b.HasIndex("PrescriptionStatusId");

                    b.HasIndex("VisitRecordId");

                    b.ToTable("Prescription", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.PrescriptionItem", b =>
                {
                    b.Property<int>("PrescriptionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionItemId"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionItemId")
                        .HasName("PK__Prescrip__1AADD9FA83ADD7FE");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionItem", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.PrescriptionStatus", b =>
                {
                    b.Property<int>("PrescriptionStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionStatusId"));

                    b.Property<string>("PrescriptionStatus1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PrescriptionStatus");

                    b.HasKey("PrescriptionStatusId")
                        .HasName("PK__Prescrip__3FC4F18C9FA63E0C");

                    b.HasIndex(new[] { "PrescriptionStatus1" }, "UQ__Prescrip__5F9A9EEFA8E95B53")
                        .IsUnique();

                    b.ToTable("PrescriptionStatus", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecializationId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SpecializationId")
                        .HasName("PK__Speciali__5809D86FC7E2815F");

                    b.HasIndex(new[] { "Name" }, "UQ__Speciali__737584F62ABE0C44")
                        .IsUnique();

                    b.ToTable("Specialization", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.VisitRecord", b =>
                {
                    b.Property<int>("VisitRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitRecordId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("VisitRecordId")
                        .HasName("PK__VisitRec__922FA65C66223DFF");

                    b.HasIndex("DoctorId");

                    b.HasIndex(new[] { "AppointmentId" }, "UQ__VisitRec__8ECDFCC3027BE4FD")
                        .IsUnique();

                    b.ToTable("VisitRecord", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClinicAPI.Models.Appointment", b =>
                {
                    b.HasOne("ClinicAPI.Models.AppointmentStatus", "AppointmentStatus")
                        .WithMany("Appointments")
                        .HasForeignKey("AppointmentStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Status");

                    b.HasOne("ClinicAPI.Models.ApplicationUser", "CreatedByAspNetUser")
                        .WithMany()
                        .HasForeignKey("CreatedByAspNetUserId")
                        .HasConstraintName("FK_Appointment_CreatedByAspNetUsers");

                    b.HasOne("ClinicAPI.Models.DoctorProfile", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Doctor");

                    b.HasOne("ClinicAPI.Models.PatientProfile", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Patient");

                    b.HasOne("ClinicAPI.Models.Specialization", "Specialization")
                        .WithMany("Appointments")
                        .HasForeignKey("SpecializationId")
                        .IsRequired()
                        .HasConstraintName("FK_Appointment_Specialization");

                    b.Navigation("AppointmentStatus");

                    b.Navigation("CreatedByAspNetUser");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("ClinicAPI.Models.AppointmentStatusHistory", b =>
                {
                    b.HasOne("ClinicAPI.Models.Appointment", "Appointment")
                        .WithMany("AppointmentStatusHistories")
                        .HasForeignKey("AppointmentId")
                        .IsRequired()
                        .HasConstraintName("FK_StatusHistory_Appointment");

                    b.HasOne("ClinicAPI.Models.AppointmentStatus", "AppointmentStatus")
                        .WithMany("AppointmentStatusHistories")
                        .HasForeignKey("AppointmentStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_StatusHistory_Status");

                    b.HasOne("ClinicAPI.Models.ApplicationUser", "ChangedByAspNetUser")
                        .WithMany()
                        .HasForeignKey("ChangedByAspNetUserId")
                        .HasConstraintName("FK_StatusHistory_ChangedByAspNetUsers");

                    b.Navigation("Appointment");

                    b.Navigation("AppointmentStatus");

                    b.Navigation("ChangedByAspNetUser");
                });

            modelBuilder.Entity("ClinicAPI.Models.DoctorLeave", b =>
                {
                    b.HasOne("ClinicAPI.Models.ApplicationUser", "ApprovedByAspNetUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByAspNetUserId")
                        .HasConstraintName("FK_DoctorLeave_ApprovedByAspNetUsers");

                    b.HasOne("ClinicAPI.Models.DoctorProfile", "Doctor")
                        .WithMany("DoctorLeaves")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_DoctorLeave_Doctor");

                    b.HasOne("ClinicAPI.Models.LeaveStatus", "LeaveStatus")
                        .WithMany("DoctorLeaves")
                        .HasForeignKey("LeaveStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_DoctorLeave_Status");

                    b.Navigation("ApprovedByAspNetUser");

                    b.Navigation("Doctor");

                    b.Navigation("LeaveStatus");
                });

            modelBuilder.Entity("ClinicAPI.Models.DoctorProfile", b =>
                {
                    b.HasOne("ClinicAPI.Models.ApplicationUser", "AspNetUser")
                        .WithMany()
                        .HasForeignKey("AspNetUserId")
                        .HasConstraintName("FK_DoctorProfile_AspNetUsers");

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("ClinicAPI.Models.DoctorSchedule", b =>
                {
                    b.HasOne("ClinicAPI.Models.DoctorProfile", "Doctor")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_DoctorSchedule_Doctor");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicAPI.Models.DoctorSpecialization", b =>
                {
                    b.HasOne("ClinicAPI.Models.DoctorProfile", "Doctor")
                        .WithMany("DoctorSpecializations")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_DoctorSpecialization_Doctor");

                    b.HasOne("ClinicAPI.Models.Specialization", "Specialization")
                        .WithMany("DoctorSpecializations")
                        .HasForeignKey("SpecializationId")
                        .IsRequired()
                        .HasConstraintName("FK_DoctorSpecialization_Specialization");

                    b.Navigation("Doctor");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("ClinicAPI.Models.Notification", b =>
                {
                    b.HasOne("ClinicAPI.Models.Appointment", "Appointment")
                        .WithMany("Notifications")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("FK_Notification_Appointment");

                    b.HasOne("ClinicAPI.Models.ApplicationUser", "AspNetUser")
                        .WithMany()
                        .HasForeignKey("AspNetUserId")
                        .HasConstraintName("FK_Notification_AspNetUsers");

                    b.HasOne("ClinicAPI.Models.NotificationType", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_Type");

                    b.Navigation("Appointment");

                    b.Navigation("AspNetUser");

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("ClinicAPI.Models.PatientProfile", b =>
                {
                    b.HasOne("ClinicAPI.Models.ApplicationUser", "AspNetUser")
                        .WithMany()
                        .HasForeignKey("AspNetUserId")
                        .HasConstraintName("FK_PatientProfile_AspNetUsers");

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("ClinicAPI.Models.Prescription", b =>
                {
                    b.HasOne("ClinicAPI.Models.PrescriptionStatus", "PrescriptionStatus")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PrescriptionStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Prescription_Status");

                    b.HasOne("ClinicAPI.Models.VisitRecord", "VisitRecord")
                        .WithMany("Prescriptions")
                        .HasForeignKey("VisitRecordId")
                        .IsRequired()
                        .HasConstraintName("FK_Prescription_VisitRecord");

                    b.Navigation("PrescriptionStatus");

                    b.Navigation("VisitRecord");
                });

            modelBuilder.Entity("ClinicAPI.Models.PrescriptionItem", b =>
                {
                    b.HasOne("ClinicAPI.Models.Prescription", "Prescription")
                        .WithMany("PrescriptionItems")
                        .HasForeignKey("PrescriptionId")
                        .IsRequired()
                        .HasConstraintName("FK_PrescriptionItem_Prescription");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("ClinicAPI.Models.VisitRecord", b =>
                {
                    b.HasOne("ClinicAPI.Models.Appointment", "Appointment")
                        .WithOne("VisitRecord")
                        .HasForeignKey("ClinicAPI.Models.VisitRecord", "AppointmentId")
                        .IsRequired()
                        .HasConstraintName("FK_VisitRecord_Appointment");

                    b.HasOne("ClinicAPI.Models.DoctorProfile", "Doctor")
                        .WithMany("VisitRecords")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_VisitRecord_Doctor");

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClinicAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicAPI.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentStatusHistories");

                    b.Navigation("Notifications");

                    b.Navigation("VisitRecord");
                });

            modelBuilder.Entity("ClinicAPI.Models.AppointmentStatus", b =>
                {
                    b.Navigation("AppointmentStatusHistories");

                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicAPI.Models.DoctorProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorLeaves");

                    b.Navigation("DoctorSchedules");

                    b.Navigation("DoctorSpecializations");

                    b.Navigation("VisitRecords");
                });

            modelBuilder.Entity("ClinicAPI.Models.LeaveStatus", b =>
                {
                    b.Navigation("DoctorLeaves");
                });

            modelBuilder.Entity("ClinicAPI.Models.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("ClinicAPI.Models.PatientProfile", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("ClinicAPI.Models.Prescription", b =>
                {
                    b.Navigation("PrescriptionItems");
                });

            modelBuilder.Entity("ClinicAPI.Models.PrescriptionStatus", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("ClinicAPI.Models.Specialization", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorSpecializations");
                });

            modelBuilder.Entity("ClinicAPI.Models.VisitRecord", b =>
                {
                    b.Navigation("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
